<a href="https://colab.research.google.com/github/DeveshGund1403/Decision-Modeling-Experiment/blob/main/Q_Learning_algorithm_EXP_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import gym

# Create the environment
env = gym.make('Taxi-v3')

# Initialize Q-table with zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])

# Set hyperparameters
alpha = 0.1  # Learning rate
gamma = 0.6  # Discount factor
epsilon = 0.1  # Exploration rate

# Number of episodes
episodes = 1000

# Q-Learning algorithm
for _ in range(episodes):
    state = env.reset()
    done = False
    while not done:
        # Epsilon-greedy policy
        if np.random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()  # Exploration
        else:
            action = np.argmax(Q[state])  # Exploitation

        next_state, reward, done, _ = env.step(action)

        # Q-value update
        old_q_value = Q[state, action]
        next_max = np.max(Q[next_state])
        new_q_value = (1 - alpha) * old_q_value + alpha * (reward + gamma * next_max)
        Q[state, action] = new_q_value

        state = next_state

# Print the learned Q-table
print("Learned Q-table:")
print(Q)

# Evaluate the learned policy
total_rewards = 0
episodes = 100
for _ in range(episodes):
    state = env.reset()
    done = False
    while not done:
        action = np.argmax(Q[state])
        state, reward, done, _ = env.step(action)
        total_rewards += reward

# Average reward over episodes
average_reward = total_rewards / episodes
print("Average Reward:", average_reward)


/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


Learned Q-table:
[[ 0.          0.          0.          0.          0.          0.        ]
 [-2.26962582 -2.27307875 -2.27989985 -2.27356044 -2.26737441 -6.25016558]
 [-1.76451912 -1.70437375 -1.71239263 -1.70063235 -0.85354384 -3.60129787]
 ...
 [-1.19052041 -0.86398813 -1.19870789 -1.17669566 -2.83039448 -3.52791771]
 [-2.00998474 -2.01671166 -2.01158462 -2.01947185 -2.8453076  -2.829299  ]
 [-0.1        -0.1        -0.1         2.59020305 -1.         -1.        ]]
Average Reward: -149.22
